### PR TITLE
Transition from readme to actually using sphinx docs

### PR DESCRIPTION
**Pull request by jakkdl**
* remove most stuff from README.md
* add links to docs in pypi and readme
* add badge for pypi and coverage to readme
* add links to contributor guide and changelog to docs

I'll probably transition the contributor guide and changelog to sphinx as well

### CODE REVIEW

**Comment by jakkdl** [comment]
When reviewing contributing.rst I recommend viewing the diff for https://github.com/python-trio/flake8-async/pull/245/commits/40bfeee88e3c4acce04e0c0d1ad4d0d3b258d0f1 separately, as I made a bunch of changes after the direct translation.

also I ran out of free tokens, oops

**Review by Zac-HD — APPROVED** [review]
Looks great 📖🚀

**Comment by Zac-HD** [comment]
Oops, we now have a semantic merge conflict where the latest changelog entry has been dropped.  Well, other than that it's ready to merge 😅

**Comment by jakkdl** [comment]
Meta tests did their job!

**Pull request merged**
